#include "Keyboard.h"
#define BACKLIGHT_INTENSITY 70
#define HOLD_THRESHOLD 500
#define DEBOUNCE_TIME 30

// Initial bank:
uint8_t currentBank = 9;

/* Initial operating system
  0: Linux
  1: Windows
  2: macOS
*/

uint8_t currentOS = 0;


/* Header generated by freeMacro genConfig v0.5
   To generate a new config, "modify banks.layout" and run genConfig,
   then place the output ("config.h") in the "freeMacro-firmware directory" */

void bank0(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
	}
}

void bank1(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
	}
}

void bank2(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_RIGHT_ALT); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
	}
}

void bank3(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('a'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('b'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('c'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('d'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('e'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('f'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('g'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('h'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('i'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('j'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('k'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('l'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('m'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('n'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('o'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press(KEY_RIGHT_CTRL); delay(2); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('p'); delay(2); Keyboard.releaseAll(); break;
		} break;
	}
}

void bank4(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.print("0x0F"); break;
			case 0x01: Keyboard.print("0x0E"); break;
			case 0x02: Keyboard.print("0x0D"); break;
			case 0x03: Keyboard.print("0x0C"); break;
			case 0x04: Keyboard.print("0x0B"); break;
			case 0x05: Keyboard.print("0x0A"); break;
			case 0x06: Keyboard.print("0x09"); break;
			case 0x07: Keyboard.print("0x08"); break;
			case 0x08: Keyboard.print("0x07"); break;
			case 0x09: Keyboard.print("0x06"); break;
			case 0x0A: Keyboard.print("0x05"); break;
			case 0x0B: Keyboard.print("0x04"); break;
			case 0x0C: Keyboard.print("0x03"); break;
			case 0x0D: Keyboard.print("0x02"); break;
			case 0x0E: Keyboard.print("0x01"); break;
			case 0x0F: Keyboard.print("0x00"); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.print("0x0F"); break;
			case 0x01: Keyboard.print("0x0E"); break;
			case 0x02: Keyboard.print("0x0D"); break;
			case 0x03: Keyboard.print("0x0C"); break;
			case 0x04: Keyboard.print("0x0B"); break;
			case 0x05: Keyboard.print("0x0A"); break;
			case 0x06: Keyboard.print("0x09"); break;
			case 0x07: Keyboard.print("0x08"); break;
			case 0x08: Keyboard.print("0x07"); break;
			case 0x09: Keyboard.print("0x06"); break;
			case 0x0A: Keyboard.print("0x05"); break;
			case 0x0B: Keyboard.print("0x04"); break;
			case 0x0C: Keyboard.print("0x03"); break;
			case 0x0D: Keyboard.print("0x02"); break;
			case 0x0E: Keyboard.print("0x01"); break;
			case 0x0F: Keyboard.print("0x00"); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.print("0x0F"); break;
			case 0x01: Keyboard.print("0x0E"); break;
			case 0x02: Keyboard.print("0x0D"); break;
			case 0x03: Keyboard.print("0x0C"); break;
			case 0x04: Keyboard.print("0x0B"); break;
			case 0x05: Keyboard.print("0x0A"); break;
			case 0x06: Keyboard.print("0x09"); break;
			case 0x07: Keyboard.print("0x08"); break;
			case 0x08: Keyboard.print("0x07"); break;
			case 0x09: Keyboard.print("0x06"); break;
			case 0x0A: Keyboard.print("0x05"); break;
			case 0x0B: Keyboard.print("0x04"); break;
			case 0x0C: Keyboard.print("0x03"); break;
			case 0x0D: Keyboard.print("0x02"); break;
			case 0x0E: Keyboard.print("0x01"); break;
			case 0x0F: Keyboard.print("0x00"); break;
		} break;
	}
}

void bank5(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.print("0x000F"); break;
			case 0x01: Keyboard.print("0x000E"); break;
			case 0x02: Keyboard.print("0x000D"); break;
			case 0x03: Keyboard.print("0x000C"); break;
			case 0x04: Keyboard.print("0x000B"); break;
			case 0x05: Keyboard.print("0x000A"); break;
			case 0x06: Keyboard.print("0x0009"); break;
			case 0x07: Keyboard.print("0x0008"); break;
			case 0x08: Keyboard.print("0x0007"); break;
			case 0x09: Keyboard.print("0x0006"); break;
			case 0x0A: Keyboard.print("0x0005"); break;
			case 0x0B: Keyboard.print("0x0004"); break;
			case 0x0C: Keyboard.print("0x0003"); break;
			case 0x0D: Keyboard.print("0x0002"); break;
			case 0x0E: Keyboard.print("0x0001"); break;
			case 0x0F: Keyboard.print("0x0000"); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.print("0x000F"); break;
			case 0x01: Keyboard.print("0x000E"); break;
			case 0x02: Keyboard.print("0x000D"); break;
			case 0x03: Keyboard.print("0x000C"); break;
			case 0x04: Keyboard.print("0x000B"); break;
			case 0x05: Keyboard.print("0x000A"); break;
			case 0x06: Keyboard.print("0x0009"); break;
			case 0x07: Keyboard.print("0x0008"); break;
			case 0x08: Keyboard.print("0x0007"); break;
			case 0x09: Keyboard.print("0x0006"); break;
			case 0x0A: Keyboard.print("0x0005"); break;
			case 0x0B: Keyboard.print("0x0004"); break;
			case 0x0C: Keyboard.print("0x0003"); break;
			case 0x0D: Keyboard.print("0x0002"); break;
			case 0x0E: Keyboard.print("0x0001"); break;
			case 0x0F: Keyboard.print("0x0000"); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.print("0x000F"); break;
			case 0x01: Keyboard.print("0x000E"); break;
			case 0x02: Keyboard.print("0x000D"); break;
			case 0x03: Keyboard.print("0x000C"); break;
			case 0x04: Keyboard.print("0x000B"); break;
			case 0x05: Keyboard.print("0x000A"); break;
			case 0x06: Keyboard.print("0x0009"); break;
			case 0x07: Keyboard.print("0x0008"); break;
			case 0x08: Keyboard.print("0x0007"); break;
			case 0x09: Keyboard.print("0x0006"); break;
			case 0x0A: Keyboard.print("0x0005"); break;
			case 0x0B: Keyboard.print("0x0004"); break;
			case 0x0C: Keyboard.print("0x0003"); break;
			case 0x0D: Keyboard.print("0x0002"); break;
			case 0x0E: Keyboard.print("0x0001"); break;
			case 0x0F: Keyboard.print("0x0000"); break;
		} break;
	}
}

void bank6(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_KP_ENTER); delay(10); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_KP_DOT); delay(10); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_KP_SLASH); delay(10); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_KP_ASTERISK); delay(10); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_KP_MINUS); delay(10); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_KP_PLUS); delay(10); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_KP_9); delay(10); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_KP_8); delay(10); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_KP_7); delay(10); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_KP_6); delay(10); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_KP_5); delay(10); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_KP_4); delay(10); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_KP_3); delay(10); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_KP_2); delay(10); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_KP_1); delay(10); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_KP_0); delay(10); Keyboard.releaseAll(); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_KP_ENTER); delay(10); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_KP_DOT); delay(10); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_KP_SLASH); delay(10); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_KP_ASTERISK); delay(10); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_KP_MINUS); delay(10); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_KP_PLUS); delay(10); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_KP_9); delay(10); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_KP_8); delay(10); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_KP_7); delay(10); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_KP_6); delay(10); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_KP_5); delay(10); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_KP_4); delay(10); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_KP_3); delay(10); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_KP_2); delay(10); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_KP_1); delay(10); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_KP_0); delay(10); Keyboard.releaseAll(); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_KP_ENTER); delay(10); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_KP_DOT); delay(10); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_KP_SLASH); delay(10); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_KP_ASTERISK); delay(10); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_KP_MINUS); delay(10); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_KP_PLUS); delay(10); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_KP_9); delay(10); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_KP_8); delay(10); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_KP_7); delay(10); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_KP_6); delay(10); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_KP_5); delay(10); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_KP_4); delay(10); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_KP_3); delay(10); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_KP_2); delay(10); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_KP_1); delay(10); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_KP_0); delay(10); Keyboard.releaseAll(); break;
		} break;
	}
}

void bank7(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("222d"); delay(5); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("222c"); delay(5); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("222b"); delay(5); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2225"); delay(5); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2222"); delay(5); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2220"); delay(5); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("221e"); delay(5); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("221d"); delay(5); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("221b"); delay(5); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("221a"); delay(5); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2219"); delay(5); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2213"); delay(5); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("001b"); delay(5); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2211"); delay(5); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2210"); delay(5); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("220f"); delay(5); Keyboard.releaseAll(); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.print("222d"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.print("222c"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.print("222b"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.print("2225"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.print("2222"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.print("2220"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.print("221e"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.print("221d"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.print("221b"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.print("221a"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.print("2219"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.print("2213"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.print("001b"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.print("2211"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.print("2210"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.print("220f"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("222d"); delay(5); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("222c"); delay(5); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("222b"); delay(5); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2225"); delay(5); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2222"); delay(5); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2220"); delay(5); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("221e"); delay(5); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("221d"); delay(5); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("221b"); delay(5); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("221a"); delay(5); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2219"); delay(5); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2213"); delay(5); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("001b"); delay(5); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2211"); delay(5); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2210"); delay(5); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("220f"); delay(5); Keyboard.releaseAll(); break;
		} break;
	}
}

void bank8(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24ab"); delay(5); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24aa"); delay(5); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24a9"); delay(5); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24a8"); delay(5); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24a7"); delay(5); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24a6"); delay(5); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24a5"); delay(5); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24a4"); delay(5); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24a3"); delay(5); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24a2"); delay(5); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24a1"); delay(5); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("24a0"); delay(5); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("249f"); delay(5); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("249e"); delay(5); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("249d"); delay(5); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("249c"); delay(5); Keyboard.releaseAll(); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.print("24ab"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.print("24aa"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.print("24a9"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.print("24a8"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.print("24a7"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.print("24a6"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.print("24a5"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.print("24a4"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.print("24a3"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.print("24a2"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.print("24a1"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.print("24a0"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.print("249f"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.print("249e"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.print("249d"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.print("249c"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24ab"); delay(5); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24aa"); delay(5); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24a9"); delay(5); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24a8"); delay(5); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24a7"); delay(5); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24a6"); delay(5); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24a5"); delay(5); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24a4"); delay(5); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24a3"); delay(5); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24a2"); delay(5); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24a1"); delay(5); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("24a0"); delay(5); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("249f"); delay(5); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("249e"); delay(5); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("249d"); delay(5); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("249c"); delay(5); Keyboard.releaseAll(); break;
		} break;
	}
}

void bank9(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03a3"); delay(5); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03a9"); delay(5); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03c9"); delay(5); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03c6"); delay(5); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03c4"); delay(5); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03c1"); delay(5); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03c0"); delay(5); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03bd"); delay(5); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03bc"); delay(5); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03bb"); delay(5); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03b8"); delay(5); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03b7"); delay(5); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("0394"); delay(5); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03b3"); delay(5); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03b2"); delay(5); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("03b1"); delay(5); Keyboard.releaseAll(); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.print("03a3"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.print("03a9"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.print("03c9"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.print("03c6"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.print("03c4"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.print("03c1"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.print("03c0"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.print("03bd"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.print("03bc"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.print("03bb"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.print("03b8"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.print("03b7"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.print("0394"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.print("03b3"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.print("03b2"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.print("03b1"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03a3"); delay(5); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03a9"); delay(5); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03c9"); delay(5); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03c6"); delay(5); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03c4"); delay(5); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03c1"); delay(5); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03c0"); delay(5); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03bd"); delay(5); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03bc"); delay(5); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03bb"); delay(5); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03b8"); delay(5); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03b7"); delay(5); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("0394"); delay(5); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03b3"); delay(5); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03b2"); delay(5); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("03b1"); delay(5); Keyboard.releaseAll(); break;
		} break;
	}
}

void bankA(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2248"); delay(5); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2261"); delay(5); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2205"); delay(5); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2220"); delay(5); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2206"); delay(5); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2234"); delay(5); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2200"); delay(5); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2203"); delay(5); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("221a"); delay(5); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("220c"); delay(5); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("220b"); delay(5); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2209"); delay(5); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2208"); delay(5); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("21d2"); delay(5); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2192"); delay(5); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_CTRL); delay(2); Keyboard.press(KEY_LEFT_SHIFT); delay(2); Keyboard.press('u'); delay(2); Keyboard.release('u'); delay(5); Keyboard.print("2190"); delay(5); Keyboard.releaseAll(); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.print("2248"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.print("2261"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.print("2205"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.print("2220"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.print("2206"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.print("2234"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.print("2200"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.print("2203"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.print("221a"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.print("220c"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.print("220b"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.print("2209"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.print("2208"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.print("21d2"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.print("2192"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.print("2190"); delay(5); Keyboard.press(KEY_LEFT_ALT); delay(2); Keyboard.press('x'); delay(2); Keyboard.releaseAll(); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2248"); delay(5); Keyboard.releaseAll(); break;
			case 0x01: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2261"); delay(5); Keyboard.releaseAll(); break;
			case 0x02: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2205"); delay(5); Keyboard.releaseAll(); break;
			case 0x03: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2220"); delay(5); Keyboard.releaseAll(); break;
			case 0x04: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2206"); delay(5); Keyboard.releaseAll(); break;
			case 0x05: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2234"); delay(5); Keyboard.releaseAll(); break;
			case 0x06: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2200"); delay(5); Keyboard.releaseAll(); break;
			case 0x07: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2203"); delay(5); Keyboard.releaseAll(); break;
			case 0x08: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("221a"); delay(5); Keyboard.releaseAll(); break;
			case 0x09: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("220c"); delay(5); Keyboard.releaseAll(); break;
			case 0x0A: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("220b"); delay(5); Keyboard.releaseAll(); break;
			case 0x0B: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2209"); delay(5); Keyboard.releaseAll(); break;
			case 0x0C: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2208"); delay(5); Keyboard.releaseAll(); break;
			case 0x0D: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("21d2"); delay(5); Keyboard.releaseAll(); break;
			case 0x0E: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2192"); delay(5); Keyboard.releaseAll(); break;
			case 0x0F: Keyboard.press(KEY_LEFT_ALT); delay(20); Keyboard.print("2190"); delay(5); Keyboard.releaseAll(); break;
		} break;
	}
}

void bankB(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.print("String F"); break;
			case 0x01: Keyboard.print("String E"); break;
			case 0x02: Keyboard.print("String D"); break;
			case 0x03: Keyboard.print("String C"); break;
			case 0x04: Keyboard.print("String B"); break;
			case 0x05: Keyboard.print("String A"); break;
			case 0x06: Keyboard.print("String 9"); break;
			case 0x07: Keyboard.print("String 8"); break;
			case 0x08: Keyboard.print("String 7"); break;
			case 0x09: Keyboard.print("String 6"); break;
			case 0x0A: Keyboard.print("String 5"); break;
			case 0x0B: Keyboard.print("String 4"); break;
			case 0x0C: Keyboard.print("String 3"); break;
			case 0x0D: Keyboard.print("String 2"); break;
			case 0x0E: Keyboard.print("String 1"); break;
			case 0x0F: Keyboard.print("Live long and prosper"); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.print("String F"); break;
			case 0x01: Keyboard.print("String E"); break;
			case 0x02: Keyboard.print("String D"); break;
			case 0x03: Keyboard.print("String C"); break;
			case 0x04: Keyboard.print("String B"); break;
			case 0x05: Keyboard.print("String A"); break;
			case 0x06: Keyboard.print("String 9"); break;
			case 0x07: Keyboard.print("String 8"); break;
			case 0x08: Keyboard.print("String 7"); break;
			case 0x09: Keyboard.print("String 6"); break;
			case 0x0A: Keyboard.print("String 5"); break;
			case 0x0B: Keyboard.print("String 4"); break;
			case 0x0C: Keyboard.print("String 3"); break;
			case 0x0D: Keyboard.print("String 2"); break;
			case 0x0E: Keyboard.print("String 1"); break;
			case 0x0F: Keyboard.print("Live long and prosper"); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.print("String F"); break;
			case 0x01: Keyboard.print("String E"); break;
			case 0x02: Keyboard.print("String D"); break;
			case 0x03: Keyboard.print("String C"); break;
			case 0x04: Keyboard.print("String B"); break;
			case 0x05: Keyboard.print("String A"); break;
			case 0x06: Keyboard.print("String 9"); break;
			case 0x07: Keyboard.print("String 8"); break;
			case 0x08: Keyboard.print("String 7"); break;
			case 0x09: Keyboard.print("String 6"); break;
			case 0x0A: Keyboard.print("String 5"); break;
			case 0x0B: Keyboard.print("String 4"); break;
			case 0x0C: Keyboard.print("String 3"); break;
			case 0x0D: Keyboard.print("String 2"); break;
			case 0x0E: Keyboard.print("String 1"); break;
			case 0x0F: Keyboard.print("Live long and prosper"); break;
		} break;
	}
}

void bankC(uint8_t keyPressed, uint8_t OS){
	switch(OS){
		case 0:
		switch(keyPressed){
			case 0x00: Keyboard.print("String 0F"); break;
			case 0x01: Keyboard.print("String 0E"); break;
			case 0x02: Keyboard.print("String 0D"); break;
			case 0x03: Keyboard.print("String 0C"); break;
			case 0x04: Keyboard.print("String 0B"); break;
			case 0x05: Keyboard.print("String 0A"); break;
			case 0x06: Keyboard.print("String 09"); break;
			case 0x07: Keyboard.print("String 08"); break;
			case 0x08: Keyboard.print("String 07"); break;
			case 0x09: Keyboard.print("String 06"); break;
			case 0x0A: Keyboard.print("String 05"); break;
			case 0x0B: Keyboard.print("String 04"); break;
			case 0x0C: Keyboard.print("String 03"); break;
			case 0x0D: Keyboard.print("String 02"); break;
			case 0x0E: Keyboard.print("String 01"); break;
			case 0x0F: Keyboard.print("Live long and prosper"); break;
		} break;
		case 1:
		switch(keyPressed){
			case 0x00: Keyboard.print("String 0F"); break;
			case 0x01: Keyboard.print("String 0E"); break;
			case 0x02: Keyboard.print("String 0D"); break;
			case 0x03: Keyboard.print("String 0C"); break;
			case 0x04: Keyboard.print("String 0B"); break;
			case 0x05: Keyboard.print("String 0A"); break;
			case 0x06: Keyboard.print("String 09"); break;
			case 0x07: Keyboard.print("String 08"); break;
			case 0x08: Keyboard.print("String 07"); break;
			case 0x09: Keyboard.print("String 06"); break;
			case 0x0A: Keyboard.print("String 05"); break;
			case 0x0B: Keyboard.print("String 04"); break;
			case 0x0C: Keyboard.print("String 03"); break;
			case 0x0D: Keyboard.print("String 02"); break;
			case 0x0E: Keyboard.print("String 01"); break;
			case 0x0F: Keyboard.print("Live long and prosper"); break;
		} break;
		case 2:
		switch(keyPressed){
			case 0x00: Keyboard.print("String 0F"); break;
			case 0x01: Keyboard.print("String 0E"); break;
			case 0x02: Keyboard.print("String 0D"); break;
			case 0x03: Keyboard.print("String 0C"); break;
			case 0x04: Keyboard.print("String 0B"); break;
			case 0x05: Keyboard.print("String 0A"); break;
			case 0x06: Keyboard.print("String 09"); break;
			case 0x07: Keyboard.print("String 08"); break;
			case 0x08: Keyboard.print("String 07"); break;
			case 0x09: Keyboard.print("String 06"); break;
			case 0x0A: Keyboard.print("String 05"); break;
			case 0x0B: Keyboard.print("String 04"); break;
			case 0x0C: Keyboard.print("String 03"); break;
			case 0x0D: Keyboard.print("String 02"); break;
			case 0x0E: Keyboard.print("String 01"); break;
			case 0x0F: Keyboard.print("Live long and prosper"); break;
		} break;
	}
}
